ALTER TABLE videos ADD COLUMN IF NOT EXISTS flagged TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS flagged_reason VARCHAR(120) DEFAULT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS original_url TEXT DEFAULT NULL;
